dataset:
  num_classes: 38
  training:
    video_mp4_path: /data/Dataset/MMAction/Task2_Cross_Modal_Untrimmed_Action_Temporal_Localization/untrimmed/video_112_2304_flow_npy
    video_info_path: /data/Dataset/MMAction/Task2_Cross_Modal_Untrimmed_Action_Temporal_Localization/untrimmed/trainval_112_2304.json
    video_anno_path: None
    video_data_path: None
    clip_length: 2304
    clip_stride: 2304
    crop_size: 96
  testing:
    video_mp4_path: /data/Dataset/MMAction/Task2_Cross_Modal_Untrimmed_Action_Temporal_Localization/untrimmed/video_112_2304_flow_npy
    video_info_path: /data/Dataset/MMAction/Task2_Cross_Modal_Untrimmed_Action_Temporal_Localization/untrimmed/trainval_112_2304.json
    video_anno_path: None
    video_data_path: None
    crop_size: 96
    clip_length: 2304
    clip_stride: 2304

model:
  in_channels: 2
  freeze_bn: true
  freeze_bn_affine: true
  backbone_model: models/i3d_models/flow_imagenet.pt

training:
  batch_size: 1
  learning_rate: 1e-4
  weight_decay: 1e-4
  max_epoch: 24
  focal_loss: true
  checkpoint_path: models/anet_flow_1_1_anchor/
  random_seed: 2020

testing:
  conf_thresh: 0.01
  top_k: 20
  nms_thresh: 0.5
  nms_sigma: 0.85
  checkpoint_path: models/anet_flow/checkpoint-24.ckpt
  output_path: output/
  output_json: detection_results.json